baseurl = "/"
theme = "hugo-flex"
title = "Ğ’Ğ¾Ğ²Ğ° + ĞĞ°ÑÑ‚Ñ | Ğ Ğ°Ğ·Ğ¾Ğ¼ 2 Ñ€Ğ¾ĞºĞ¸ ğŸ‰ğŸ‰"

[params]
color = "black"
width = "42rem"
divider = "\\a0"
rss = "To subscribe to this RSS feed, copy its address and paste it into your favorite feed reader."
noClasses = true
headingoffset = 0
linkicons = false
summaries = false
schema = false
opengraph = true
twittercards = false
footer = ' '

[[menu.nav]]


[mediaTypes."font/woff2"]
suffixes = [ "woff2" ]

[pagination]
  order = "asc"  # Set the order to "desc" for reverse chronological order
  perPage = 10    # Number of posts to display per page